[package]
name = "example_repo"
version = "0.1.0"
authors = ["Kevin C. Zimmerman <kzimmerman@mru.medical.canon>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
